PharmacyManagement/PharmacyManagement/Controllers/PharmacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PharmacyManagement.Models;

namespace PharmacyManagement.Controllers
{
    public class PharmacyController : Controller
    {
        public IActionResult Index()
        {
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            User obj = new User { Email = "admin", Pwd = "admin" };
            using (HttpClient client = new HttpClient(clientHandler))
            {
                var token = GetToken("https://localhost:44353/api/Token", obj);
                client.BaseAddress = new Uri("https://localhost:44319/api/");
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = new HttpResponseMessage();
                response = client.GetAsync("Medicines").Result;
                string stringData = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<IEnumerable<Medicine>>(stringData);
                return View(data);
            }
        }
        public IActionResult Index1()
        {
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            User obj = new User { Email = "admin", Pwd = "admin" };
            using (HttpClient client = new HttpClient(clientHandler))
            {
                var token = GetToken("https://localhost:44353/api/Token", obj);
                client.BaseAddress = new Uri("https://localhost:44328/api/");
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = new HttpResponseMessage();
                response = client.GetAsync("OrderItems").Result;
                string stringData = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<IEnumerable<OrderItem>>(stringData);
                return View(data);
            }
        }
        public IActionResult Index2()
        {
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            User obj = new User { Email = "admin", Pwd = "admin" };
            using (HttpClient client = new HttpClient(clientHandler))
            {
                var token = GetToken("https://localhost:44353/api/Token", obj);
                client.BaseAddress = new Uri("https://localhost:44394/api/");
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = new HttpResponseMessage();
                response = client.GetAsync("Customers").Result;
                string stringData = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<IEnumerable<Customer>>(stringData);
                return View(data);
            }
        }
        static string GetToken(string url, User user)
        {
            var json = JsonConvert.SerializeObject(user);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            using (HttpClient client = new HttpClient(clientHandler))
            {
                var response = client.PostAsync(url, data).Result;
                string name = response.Content.ReadAsStringAsync().Result;
                dynamic details = JObject.Parse(name);
                return details.token;
            }
        }
    }
}

PharmacyManagement/PharmacyManagement/Views/Pharmacy/Index.cshtml
@model IEnumerable<PharmacyManagement.Models.Medicine>

@{
    ViewData["Title"] = "Index";
}

<h1>Medicine Details</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MedicineId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MedicineName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpiryDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicineId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicineName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpiryDate)
                </td>
                <td>
                    <input type="button" name="button" value="Select Medicine" />
                </td>
            </tr>
        }
    </tbody>
</table>
<br>
<br>
<a asp-controller="Pharmacy" asp-action="Index1">Order Item List</a>

PharmacyManagement/PharmacyManagement/Views/Pharmacy/Index1.cshtml
@model IEnumerable<PharmacyManagement.Models.OrderItem>

@{
    ViewData["Title"] = "Index1";
}

<h1>Order Details</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfPurchase)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfPurchase)
                </td>
            </tr>
        }
    </tbody>
</table>
<br>
<br>
<a asp-controller="Pharmacy" asp-action="Index2">Open Customer List Here</a>

PharmacyManagement/PharmacyManagement/Views/Pharmacy/Index2.cshtml
@model IEnumerable<PharmacyManagement.Models.Customer>

@{
    ViewData["Title"] = "Index2";
}

<h1>Customer Details</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
            </tr>
        }
    </tbody>
</table>